"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("@storybook/react");
var Table_1 = require("./Table");
var Label_1 = require("./../Label/Label");
var ButtonLink_1 = require("./../ButtonLink/ButtonLink");
var Avatar_1 = require("./../Avatar/Avatar");
var Typography_1 = require("./../Typography/Typography");
var Button_1 = require("./../Button/Button");
var Icon_1 = require("./../Icon/Icon");
var utils_1 = require("../../utils");
var react_2 = require("@storybook/addon-knobs/react");
var Profile = require("./../../images/profile-pic.svg");
react_1.storiesOf("Components/Table", module).addWithJSX("Eximchain Table", utils_1.wInfo("\n    ### Note\n    example Table story\n    ### Usage\n    ~~~js\n    <Table >\n      <thead>\n        <tr>\n          <th>Tx Hash <a href=\"#\"><i className=\"fa fa-arrow-down\"></i></a></th>\n          <th>Date</th>\n          <th>From</th>\n          <th>To</th>\n          <th>Amount</th>\n          <th>Fee</th>\n          <th>Status</th>\n        </tr>\n      </thead>\n\n      <tbody>\n        <tr>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>10-31-17</td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>0.001504 EXC</td>\n          <td>0.000504</td>\n          <td><Label status=\"received\">Received</Label></td>\n        </tr>\n        .....\n        <tr>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>10-31-17</td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>0.001504 EXC</td>\n          <td>0.000504</td>\n          <td><Label status=\"received\">Received</Label></td>\n        </tr>\n      </tbody>\n    </Table>\n\n    ~~~")(function () { return (React.createElement("div", null,
    React.createElement(Table_1.Table, null,
        React.createElement("thead", null,
            React.createElement("tr", null,
                React.createElement("th", null,
                    "Tx Hash ",
                    React.createElement("a", { href: "#" },
                        React.createElement("i", { className: "fa fa-arrow-down" }))),
                React.createElement("th", null, "Date"),
                React.createElement("th", null, "From"),
                React.createElement("th", null, "To"),
                React.createElement("th", null, "Amount"),
                React.createElement("th", null, "Fee"),
                React.createElement("th", null, "Status"))),
        React.createElement("tbody", null,
            React.createElement("tr", null,
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "10-31-17"),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "0.001504 EXC"),
                React.createElement("td", null, "0.000504"),
                React.createElement("td", null,
                    React.createElement(Label_1.Label, { status: "received" }, "Received"))),
            React.createElement("tr", null,
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "10-31-17"),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "0.001504 EXC"),
                React.createElement("td", null, "0.000504"),
                React.createElement("td", null,
                    React.createElement(Label_1.Label, { status: "received" }, "Received"))),
            React.createElement("tr", null,
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "10-31-17"),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null,
                    React.createElement(ButtonLink_1.ButtonLink, { address: true }, "0x62282668b")),
                React.createElement("td", null, "0.001504 EXC"),
                React.createElement("td", null, "0.000504"),
                React.createElement("td", null,
                    React.createElement(Label_1.Label, { status: "received" }, "Received"))))),
    React.createElement("div", { className: "table-member" },
        React.createElement(Table_1.Table, null,
            React.createElement("thead", null,
                React.createElement("tr", null,
                    React.createElement("th", null,
                        "Name ",
                        React.createElement("a", { href: "#" },
                            React.createElement("i", { className: "fa fa-arrow-down" }))),
                    React.createElement("th", null, "Addresses"),
                    React.createElement("th", null, "Nationality"),
                    React.createElement("th", null, "Member since"),
                    React.createElement("th", null, "Cycle Participation"),
                    React.createElement("th", null,
                        React.createElement("a", { href: "#" },
                            React.createElement("i", { className: "fa fa-bars", "aria-hidden": "true" }))))),
            React.createElement("tbody", null,
                React.createElement("tr", null,
                    React.createElement("td", null,
                        React.createElement(Avatar_1.Avatar, { src: Profile }),
                        React.createElement(Typography_1.Typography, { useFor: 'plexMonoMed' }, "Katie Lau")),
                    React.createElement("td", null, "2"),
                    React.createElement("td", null, "Greek"),
                    React.createElement("td", null, "03/05/2018"),
                    React.createElement("td", null, "65%"),
                    React.createElement("td", null,
                        React.createElement(Button_1.ButtonSmall, null, react_2.text("Button Title", "Nominate")),
                        React.createElement(Button_1.ButtonSmall, null,
                            React.createElement(Icon_1.Icon, { for: 'more' })))),
                React.createElement("tr", null,
                    React.createElement("td", null,
                        React.createElement(Avatar_1.Avatar, { src: Profile }),
                        React.createElement(Typography_1.Typography, { useFor: 'plexMonoMed' }, "Katie Lau")),
                    React.createElement("td", null, "2"),
                    React.createElement("td", null, "Greek"),
                    React.createElement("td", null, "03/05/2018"),
                    React.createElement("td", null, "65%"),
                    React.createElement("td", null,
                        React.createElement(Button_1.ButtonSmall, null, react_2.text("Button Title", "Nominate")),
                        React.createElement(Button_1.ButtonSmall, null,
                            React.createElement(Icon_1.Icon, { for: 'more' })))),
                React.createElement("tr", null,
                    React.createElement("td", null,
                        React.createElement(Avatar_1.Avatar, { src: Profile }),
                        React.createElement(Typography_1.Typography, { useFor: 'plexMonoMed' }, "Katie Lau")),
                    React.createElement("td", null, "2"),
                    React.createElement("td", null, "Greek"),
                    React.createElement("td", null, "03/05/2018"),
                    React.createElement("td", null, "65%"),
                    React.createElement("td", null,
                        React.createElement(Button_1.ButtonSmall, null, react_2.text("Button Title", "Nominate")),
                        React.createElement(Button_1.ButtonSmall, null,
                            React.createElement(Icon_1.Icon, { for: 'more' })))),
                React.createElement("tr", null,
                    React.createElement("td", null,
                        React.createElement(Avatar_1.Avatar, { src: Profile }),
                        React.createElement(Typography_1.Typography, { useFor: 'plexMonoMed' }, "Katie Lau")),
                    React.createElement("td", null, "2"),
                    React.createElement("td", null, "Greek"),
                    React.createElement("td", null, "03/05/2018"),
                    React.createElement("td", null, "65%"),
                    React.createElement("td", null,
                        React.createElement(Button_1.ButtonSmall, null, react_2.text("Button Title", "Nominate")),
                        React.createElement(Button_1.ButtonSmall, null,
                            React.createElement(Icon_1.Icon, { for: 'more' })))),
                React.createElement("tr", null,
                    React.createElement("td", null,
                        React.createElement(Avatar_1.Avatar, { src: Profile }),
                        React.createElement(Typography_1.Typography, { useFor: 'plexMonoMed' }, "Katie Lau")),
                    React.createElement("td", null, "2"),
                    React.createElement("td", null, "Greek"),
                    React.createElement("td", null, "03/05/2018"),
                    React.createElement("td", null, "65%"),
                    React.createElement("td", null,
                        React.createElement(Button_1.ButtonSmall, null, react_2.text("Button Title", "Nominate")),
                        React.createElement(Button_1.ButtonSmall, null,
                            React.createElement(Icon_1.Icon, { for: 'more' }))))))))); })).addWithJSX("Eximchain Table with data", utils_1.wInfo("\n    ### Note\n    example Table story\n    ### Usage\n    ~~~js\n    <Table >\n      <thead>\n        <tr>\n          <th>Tx Hash <a href=\"#\"><i className=\"fa fa-arrow-down\"></i></a></th>\n          <th>Date</th>\n          <th>From</th>\n          <th>To</th>\n          <th>Amount</th>\n          <th>Fee</th>\n          <th>Status</th>\n        </tr>\n      </thead>\n\n      <tbody>\n        <tr>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>10-31-17</td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>0.001504 EXC</td>\n          <td>0.000504</td>\n          <td><Label status=\"received\">Received</Label></td>\n        </tr>\n        .....\n        <tr>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>10-31-17</td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td><ButtonLink address>0x62282668b</ButtonLink></td>\n          <td>0.001504 EXC</td>\n          <td>0.000504</td>\n          <td><Label status=\"received\">Received</Label></td>\n        </tr>\n      </tbody>\n    </Table>\n\n    ~~~")(function () {
    var columns = [{ title: 'Name', field: 'name' }, { title: 'Age', field: 'age' }];
    var records = [{ name: 'Jhon', age: 47 }, { name: 'Smith', age: 32 }];
    return (React.createElement("div", null,
        React.createElement(Table_1.Table, { columns: columns, records: records })));
}));
//# sourceMappingURL=Table.stories.js.map